create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  email text,
  message text not null,
  source text not null default 'website',
  property_id text,
  consent boolean not null default false,
  page_url text,
  status text not null default 'new'
);

alter table public.leads enable row level security;

-- Browser clients receive no direct table policy. Inserts are performed only
-- by the Vercel function with the server-side service role key.
